spring:
  jmx:
    enabled: false

modem:
#  port: /dev/tty.usbserial-A40090EW
#  speed: 115200
#  flow-control: RTSCTS
#  port: /dev/tty.Marie-Louise-SerialPort1
#  speed: 115200
#  flow-control: NONE
#  port: /dev/tty.usbmodem14207
#  speed: 7200000
#  flow-control: RTSCTS
  port: /dev/ttyUSB3
  speed: 115200
  flow-control: NONE

smpp:
  service-type: CMT
  #  possible SMSC default alphabets: CCGSM, CCPGSM, SCGSM, SCPGSM, ASCII, ISO-8859-1
  charset: CCGSM
  port: 2075
  bind-timeout: 5000
  enquire-link-timer: 300000
  transaction-timer: 15000

logging:
  file:
    name: /var/opt/jsmpp-modem/jsmpp-modem.log
  level:
    com.github.pmoerenhout.atcommander: info
    com.github.pmoerenhout.jsmpp-pool: info
    com.github.pmoerenhout: info
    com.github.pmoerenhout.jsmppmodem.service.PduService: warn
    org.jsmpp: info

---

spring:
  profiles: development

modem:
#  port: /dev/tty.usbserial-A40090EW
#  speed: 115200
#  flow-control: RTSCTS
#  port: /dev/tty.Marie-Louise-SerialPort1
#  speed: 115200
#  flow-control: NONE
  port: /dev/tty.usbmodem14207
  speed: 7200000
  flow-control: RTSCTS

  logging:
    file:
      name:
    level:
      com.github.pmoerenhout.atcommander: trace
      com.github.pmoerenhout.jsmpp-pool: info
      com.github.pmoerenhout: info
      org.jsmpp: debug
